### ISSUE TITLE
How do i bring the menu up?

### ISSUE THREAD

**Issue by Filip-Prokop** [Pegoth/BlessingHelper#8]
Installed this addon today. It shows up in my ingame Addon list, but i cant find any button/command, to bring the interface up.

**Comment by Pegoth** [comment]
I stopped playing with classic, so this addon is not updated, but there should be a minimap icon for it. If not check the interface settings.

**Comment by Filip-Prokop** [comment]
Yeah, checked interface settings, but its not there

**Comment by Pegoth** [comment]
Maybe the addon is not enabled, because of the version miss match or something changed in the API and it does not work anymore. Unfortunately I cannot check as I don't play.

**Comment by Filip-Prokop** [comment]
Everything looks fine in Addon settings tab, so i guess they must've changed something. Thank you for your time.

**Comment by Pegoth** [comment]
@Oyster91 Hello, I started playing TBC Classic again, tried the addon with my paladin and everything seems to be working for me. Do you still have the problem?
