### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [Pegoth/BlessingHelper#9]
This mod is not working for me. All I see is a black background with the names of my party members and 00:00. If I middle click on a name, it will select the character, however; the rest of the features do not work for me. Neither left nor right clicking does anything. There are no 'icons' on the bar anywhere, and if I manually cast a blessing on someone, the timer does not change from the 00:00. I'm not sure what is wrong here.

**Comment by Pegoth** [comment]
Hello, are you using the latest version (1.3) and on WOTLK pre-patch? Are you in raid? Currently raid is unstable, already working on it.

**Comment by Glitched-Fox-Studios** [comment]
Yes, Yes, and no. In a party with roomie.

**Comment by Pegoth** [comment]
Do you have any other addons installed? if so can you send me a list?

**Comment by Glitched-Fox-Studios** [comment]
AdiBags, ArkInventory, Atlas, AtlasLootClassic, Auctionator, BVP, Classic Floating Combat Text, DBM, GatherMate 2 Classic, Handy Notes, MobInfo2, Quartz, Scrap, SexyMap, ThreatPlates, Titan Panel,

**Comment by Pegoth** [comment]
What is BVP? Better Vendor Price?

**Comment by Glitched-Fox-Studios** [comment]
Yes

**Comment by Pegoth** [comment]
Then I have no idea, installed every addon you listed, and it worked for me. Can you disable all addons except BlessingHelper and see if it is still bad?

**Comment by Glitched-Fox-Studios** [comment]
Sure. I'll check when I get home and will report back.

**Comment by Glitched-Fox-Studios** [comment]
Sorry it's taken me a bit to get back to you on this. Anyways, the newest version seems to have fixed whatever the issue was and it works just fine for me now.

EDIT: Might I make a suggestion for the next version? Instead of using the options screen for moving the container around, is it possible to add an option to be able to drag it with the mouse?
